---
title: "TER - Résultats - nback"
output:
  html_notebook:
    theme: default
    code_folding: hide
  pdf_document: default
---

```{r}

library(tidyverse)
library(ggpubr)
library(rstatix)
library(xtable)
library(wesanderson)

```


# N-Back


```{r}

nback <- read.csv2("data/nback.csv", sep = ",", fileEncoding="UTF-8-BOM")

nback$groupe <- as.factor(nback$groupe)
nback$subject_id <- as.factor(nback$subject_id)
nback$part <- factor(nback$part, levels = c("2_back_pre", "2_back_post"))
nback$id_2_back <- as.factor(nback$id_2_back)
nback$trial_id <- as.factor(nback$trial_id)
nback$rt <- as.numeric(nback$rt)

nback[is.na(nback)] <- 0

nback <- nback %>%
  filter(subject_id != 13) # trop de no-input

nback_summary <- nback %>%
  group_by(groupe, part) %>%
  summarize_if(is.numeric, mean)

nback_transc <- nback %>%
  filter(groupe == "transc")

nback_control <- nback %>%
  filter(groupe == "control")

nback_summary


```

## Temps de réponse

```{r}

nback_rt <- nback

nback_rt %>%
  group_by(groupe, part) %>%
  get_summary_stats(rt, type = "mean_sd")

```

```{r}

out_rt <- boxplot.stats(nback_rt$rt)$out


nback_rt <- nback_rt %>%
  filter(!rt %in% out_rt)

ggboxplot(nback_rt, x = "groupe", y = "rt", fill = "part")


```

```{r}

rt_densit <- ggdensity(nback_rt, x = "rt", fill = "part", main = "Densité RT", facet.by = "groupe") 
rt_densit %>%
  ggexport(filename = "Plots/rt_densit.pdf")
rt_densit

```

```{r}

ggqqplot(nback_rt, x = "rt", facet.by = c("groupe", "part"))

```

### Shapiro

```{r}

nback_rt %>%
  group_by(groupe, part) %>%
  shapiro_test(rt)

```



```{r}

rt_means <- ggbarplot(nback_rt, x = "groupe", y = "rt", fill = "part", position = position_dodge(0.8), add = "mean_sd", xlab = "Groupe", ylab = "Temps de réponse") +
  scale_fill_discrete(name = "Moment", labels = c("Pré-test", "Post-test"))

rt_means %>%
  ggexport(filename = "Plots/rt_means.pdf")

rt_means

```

### ANOVA

```{r}

nback_ind_rt <- nback_rt %>%
  group_by(groupe, part, subject_id) %>%
  summarise_if(is.numeric, mean)

nback_ind_rt %>%
  ungroup %>%
  anova_test(dv = rt, wid = subject_id, between = groupe, within = part)

```
#### Controle

```{r}
nback_ind_rt %>%
  filter(groupe == "control") %>%
  ungroup %>%
  anova_test(dv = Score, wid = subject_id, within = part)
```

#### Epuisement

```{r}
nback_ind_rt %>%
  filter(groupe == "transc") %>%
  ungroup %>%
  anova_test(dv = Score, wid = subject_id, within = part)
```


## Performances


```{r}
nback_score <- nback %>%
  group_by(groupe, subject_id, part, id_2_back) %>%
  summarise_if(is.numeric, mean)

nback_score %>%
  group_by(groupe, part) %>%
  get_summary_stats(Score, type = "mean_sd")
```

```{r}
ggboxplot(nback_score, x = "groupe", y = "Score", fill = "part")
```


```{r}
ggdensity(nback_score, x = "Score", fill = "part", main = "Densité Performances", facet.by = c("groupe", "part"), add = "mean")
```

```{r}
ggqqplot(nback_score, x = "Score", facet.by = c("groupe", "part"))
```

### Shapiro

```{r}
nback_score %>%
  group_by(groupe, part) %>%
  shapiro_test(Score)
```


```{r}
perf <- ggbarplot(nback_score, x = "groupe", y = "Score", fill = "part", position = position_dodge(0.8), add = "mean_sd") +
  scale_fill_discrete(name = "Moment", labels = c("Pré-test", "Post-test"))

perf %>%
  ggexport(filename = "Plots/perf.pdf")

perf
```


### ANOVA

```{r}
ggqqplot(nback_score, x = "Score", facet.by = c("groupe", "part"))
```


```{r}

nback_ind_perf <- nback_score %>%
  group_by(groupe, part, subject_id) %>%
  summarise_if(is.numeric, mean)

nback_ind_perf %>%
  ungroup %>%
  anova_test(dv = Score, wid = subject_id, between = groupe, within = part)

```

#### Controle

```{r}
nback_ind_perf %>%
  filter(groupe == "control") %>%
  ungroup %>%
  anova_test(dv = Score, wid = subject_id, within = part)
```

#### Epuisement

```{r}
nback_ind_perf %>%
  filter(groupe == "transc") %>%
  ungroup %>%
  anova_test(dv = Score, wid = subject_id, within = part)
```

```{r}
nbackZ <- nback_score
nbackZ$Score <- scale(nbackZ$Score)

nbackZ %>%
  group_by(groupe, part) %>%
  get_summary_stats(Score, type = "mean_sd")

```




# Delta

















