---
title: "TER - Résultats - rspan"
output:
  html_notebook:
    theme: default
    code_folding: hide
  pdf_document: 
    latex_engine: xelatex
---

```{r}

library(tidyverse)
library(ggpubr)
library(rstatix)

```

# RSPAN

## Phrases

```{r}

rspan <- read.csv2("data/rspan_dist.csv", sep = ",", fileEncoding="UTF-8-BOM")
rspan$part <- factor(rspan$part, levels = c("sentence-pre", "sentence-post", "recall-pre", "recall-post"))
rspan$size <- factor(rspan$size, levels = c("4.0", "5.0", "6.0"))
rspan$sim <- as.numeric(rspan$sim)
rspan$dsit <- as.numeric(rspan$dist)

rspan <- rspan %>%
  filter(subject_id != 4) %>%
  filter(subject_id != 30)

recall <- rspan %>%
  filter(part != 'sentence-pre') %>%
  filter(part != 'sentence-post')

sent <- rspan %>%
  filter(part != 'recall-pre') %>%
  filter(part != 'recall-post')

sent <- sent %>%
  group_by(groupe, part, subject_id) %>%
  summarise(correct = mean(correct)) 

sent %>%
  get_summary_stats(correct, type = "mean_sd")


```


```{r}
recall <- recall %>%
  group_by(groupe, subject_id, part, size) %>%
  summarise(sim = mean(sim))

recall %>%
  group_by(groupe, part, size) %>%
  get_summary_stats(sim, type = "mean_sd")

```


```{r}

ggdensity(sent, x = "correct", fill = "part", facet.by = "groupe")
ggqqplot(sent, x="correct", facet.by = c("groupe", "part"))

```


```{r}

ggbarplot(sent, x = "groupe", y = "correct", fill = "part", add = "mean_se", position = position_dodge(0.8), palette = "jco")

```


## Rappel


```{r}

ggdensity(recall, x = "sim", fill = "part", facet.by = c("groupe", "size"), palette = "jco")
ggqqplot(recall, x = "sim", color = "part", facet.by = c("groupe", "part"), palette = "jco")

```

```{r}
recall %>%
  group_by(groupe, part) %>%
  shapiro_test(sim)
```


```{r}

rspan_score <- ggbarplot(recall, x = "groupe", y = "sim", fill = "part", add = "mean_se", position = position_dodge(0.8), palette = "jco")

rspan_score %>%
  ggexport(filename = "Plots/rspan_score.pdf")

rspan_score

```

```{r}

recall_transc <- recall %>%
  filter(groupe == "transc")

rspan_size_transc <- ggbarplot(recall_transc, x = "size", y = "sim", fill = "part", add = "mean_se", position = position_dodge(0.8), facet.by = "groupe", palette = "jco")

rspan_size_transc %>%
  ggexport(filename = "Plots/rspan_size_transc.pdf", pointsize = 14)

rspan_size_transc

```

```{r}

recall_control <- recall %>%
  filter(groupe == "control")

rspan_size_control <- ggbarplot(recall_control, x = "size", y = "sim", fill = "part", add = "mean_se", position = position_dodge(0.8), facet.by = "groupe", palette = "jco")

rspan_size_control %>%
  ggexport(filename = "Plots/rspan_size_control.pdf")

rspan_size_control

```

# ANOVA

## Phrases

```{r}
sent_ind <- sent %>%
  group_by(groupe, subject_id, part) %>%
  summarise_if(is.numeric, mean)

sent_ind %>%
  ungroup%>%
  anova_test(dv = correct, wid = subject_id, between = groupe, within = part) %>%
  get_anova_table()

```

### "Part" par "groupe"

```{r}
sent_ind %>%
  group_by(groupe) %>%
  anova_test(dv = correct, wid = subject_id, within = part) %>%
  get_anova_table()
```

## Recall

```{r}
sent_rec <- recall %>%
  group_by(groupe, subject_id, part) %>%
  summarise_if(is.numeric, mean)

sent_rec %>%
  ungroup%>%
  anova_test(dv = sim, wid = subject_id, between = groupe, within = part) %>%
  get_anova_table()
```

### "Part" par "groupe"

```{r}
sent_rec %>%
  group_by(groupe) %>%
  anova_test(dv = sim, wid = subject_id, within = part) %>%
  get_anova_table()
```

### Size

```{r}
rec_size <- recall %>%
  group_by(groupe, subject_id, part, size) %>%
  summarise(sim = mean(sim))

rec_size %>%
  ungroup %>%
  group_by(groupe) %>%
  anova_test(dv = sim, within = c(size, part), wid = subject_id) %>%
  get_anova_table()
```

```{r}
rec_size %>%
  ungroup %>%
  group_by(groupe, part) %>%
  anova_test(dv = sim, within = size, wid = subject_id) %>%
  get_anova_table()
```

```{r}
rec_size %>%
  ungroup %>%
  group_by(groupe, size) %>%
  pairwise_t_test(sim ~ part, paired = T) 
```

```{r}

ggbarplot(rec_size, x = "size", y = "sim", fill = "part", add = "mean_se", position = position_dodge(0.8), facet.by = "groupe", palette = "jco")

```


# Corrélation

```{r}
rec_cor_transc <- rec_size %>%
  group_by(groupe, subject_id, part) %>%
  summarise(sim = mean(sim)) %>%
  pivot_wider(names_from = part, values_from = sim) %>%
  ungroup %>%
  filter(groupe == "transc")

cor.test(rec_cor_transc$`recall-post`, rec_cor_transc$`recall-pre`)

```

```{r}
rec_cor_cont <- rec_size %>%
  group_by(groupe, subject_id, part) %>%
  summarise(sim = mean(sim)) %>%
  pivot_wider(names_from = part, values_from = sim) %>%
  ungroup %>%
  filter(groupe == "control")

cor.test(rec_cor_cont$`recall-post`, rec_cor_cont$`recall-pre`)

```















```{r}
recall_ind <- recall %>%
  group_by(groupe, subject_id, part) %>%
  get_summary_stats(sim, type = "mean_sd")

write.csv(recall_ind, "data/recall_ind.csv")
```





